import Nav from "@/components/nav";
import Footer from "@/components/footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | Range Shipping",
  description: "Privacy Policy for Range Shipping Ltd.",
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <Nav />
      <main className="pt-[88px] bg-[#001a36] min-h-screen">
        <div className="max-w-3xl mx-auto px-6 md:px-12 py-20 md:py-28">

          <p className="text-[10px] font-medium tracking-[0.35em] uppercase text-white/35 mb-4">
            Last updated: April 17, 2022
          </p>
          <h1 className="text-3xl md:text-4xl font-bold text-white mb-12 tracking-tight">
            Privacy Policy
          </h1>

          <div className="space-y-10 text-[14px] font-light leading-relaxed text-white/60">

            <p>
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p>
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>

            <Section title="Interpretation and Definitions">
              <SubSection title="Interpretation">
                <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
              </SubSection>
              <SubSection title="Definitions">
                <p className="mb-4">For the purposes of this Privacy Policy:</p>
                <ul className="space-y-3 list-none">
                  <DefItem term="Account">a unique account created for You to access our Service or parts of our Service.</DefItem>
                  <DefItem term="Company">(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Range Shipping Ltd, Millbank Tower, 21-24 Millbank, 1st Floor, 1.5A, London, SW1P 4QP.</DefItem>
                  <DefItem term="Cookies">small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</DefItem>
                  <DefItem term="Country">United Kingdom.</DefItem>
                  <DefItem term="Device">any device that can access the Service such as a computer, a cellphone or a digital tablet.</DefItem>
                  <DefItem term="Personal Data">any information that relates to an identified or identifiable individual.</DefItem>
                  <DefItem term="Service">the Website.</DefItem>
                  <DefItem term="Service Provider">any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</DefItem>
                  <DefItem term="Usage Data">data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</DefItem>
                  <DefItem term="Website">Range Shipping Ltd, accessible from rangeshipping.com.</DefItem>
                  <DefItem term="You">the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</DefItem>
                </ul>
              </SubSection>
            </Section>

            <Section title="Collecting and Using Your Personal Data">
              <SubSection title="Types of Data Collected">
                <p className="text-white/50 font-medium mb-3">Personal Data</p>
                <p className="mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                <ul className="space-y-1 pl-4 list-disc list-outside marker:text-white/30">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Usage Data</li>
                </ul>
              </SubSection>
              <SubSection title="Usage Data">
                <p className="mb-4">Usage Data is collected automatically when using the Service.</p>
                <p className="mb-4">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                <p className="mb-4">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
              </SubSection>
              <SubSection title="Tracking Technologies and Cookies">
                <p className="mb-4">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                <ul className="space-y-4 pl-4 list-disc list-outside marker:text-white/30 mb-6">
                  <li><span className="text-white/75">Cookies or Browser Cookies.</span> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                  <li><span className="text-white/75">Flash Cookies.</span> Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies.</li>
                  <li><span className="text-white/75">Web Beacons.</span> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
                </ul>
                <p className="mb-6">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
                <p className="mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>
                <div className="space-y-4">
                  <CookieItem type="Necessary / Essential Cookies" cookieType="Session Cookies" admin="Us">These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</CookieItem>
                  <CookieItem type="Cookies Policy / Notice Acceptance Cookies" cookieType="Persistent Cookies" admin="Us">These Cookies identify if users have accepted the use of cookies on the Website.</CookieItem>
                  <CookieItem type="Functionality Cookies" cookieType="Persistent Cookies" admin="Us">These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</CookieItem>
                </div>
              </SubSection>
            </Section>

            <Section title="Use of Your Personal Data">
              <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
              <ul className="space-y-3 pl-4 list-disc list-outside marker:text-white/30 mb-6">
                <li><span className="text-white/75">To provide and maintain our Service,</span> including to monitor the usage of our Service.</li>
                <li><span className="text-white/75">To manage Your Account:</span> to manage Your registration as a user of the Service.</li>
                <li><span className="text-white/75">For the performance of a contract:</span> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                <li><span className="text-white/75">To contact You:</span> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services.</li>
                <li><span className="text-white/75">To provide You</span> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about.</li>
                <li><span className="text-white/75">To manage Your requests:</span> To attend and manage Your requests to Us.</li>
                <li><span className="text-white/75">For business transfers:</span> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
                <li><span className="text-white/75">For other purposes:</span> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.</li>
              </ul>
              <p className="mb-4">We may share Your personal information in the following situations:</p>
              <ul className="space-y-3 pl-4 list-disc list-outside marker:text-white/30">
                <li><span className="text-white/75">With Service Providers:</span> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
                <li><span className="text-white/75">For business transfers:</span> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
                <li><span className="text-white/75">With Affiliates:</span> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
                <li><span className="text-white/75">With business partners:</span> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
                <li><span className="text-white/75">With other users:</span> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
                <li><span className="text-white/75">With Your consent:</span> We may disclose Your personal information for any other purpose with Your consent.</li>
              </ul>
            </Section>

            <Section title="Retention of Your Personal Data">
              <p className="mb-4">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
              <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
            </Section>

            <Section title="Transfer of Your Personal Data">
              <p className="mb-4">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
              <p className="mb-4">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
              <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
            </Section>

            <Section title="Disclosure of Your Personal Data">
              <SubSection title="Business Transactions">
                <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
              </SubSection>
              <SubSection title="Law Enforcement">
                <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
              </SubSection>
              <SubSection title="Other Legal Requirements">
                <p className="mb-4">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                <ul className="space-y-2 pl-4 list-disc list-outside marker:text-white/30">
                  <li>Comply with a legal obligation</li>
                  <li>Protect and defend the rights or property of the Company</li>
                  <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                  <li>Protect the personal safety of Users of the Service or the public</li>
                  <li>Protect against legal liability</li>
                </ul>
              </SubSection>
            </Section>

            <Section title="Security of Your Personal Data">
              <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
            </Section>

            <Section title="Detailed Information on the Processing of Your Personal Data">
              <p className="mb-4">The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.</p>
              <SubSection title="Usage, Performance and Miscellaneous">
                <p className="mb-4">We may use third-party Service Providers to provide better improvement of our Service.</p>
                <p><span className="text-white/75">Invisible reCAPTCHA</span> — Their Privacy Policy can be viewed at{" "}
                  <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-white/60 underline underline-offset-2 hover:text-white transition-colors">
                    https://policies.google.com/privacy
                  </a>
                </p>
              </SubSection>
            </Section>

            <Section title="Children's Privacy">
              <p className="mb-4">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
              <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
            </Section>

            <Section title="Links to Other Websites">
              <p className="mb-4">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
              <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
            </Section>

            <Section title="Changes to this Privacy Policy">
              <p className="mb-4">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
              <p className="mb-4">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
              <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
            </Section>

            <Section title="Contact Us">
              <p className="mb-2">If you have any questions about this Privacy Policy, You can contact us:</p>
              <p>
                By email:{" "}
                <a href="mailto:info@rangeshipping.com" className="text-white/60 underline underline-offset-2 hover:text-white transition-colors">
                  info@rangeshipping.com
                </a>
              </p>
            </Section>

          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="text-[11px] font-semibold tracking-[0.25em] uppercase text-white/40 mb-5 border-t border-white/8 pt-8">
        {title}
      </h2>
      <div className="space-y-6">{children}</div>
    </div>
  );
}

function SubSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 className="text-[13px] font-medium text-white/50 mb-3">{title}</h3>
      <div className="space-y-3">{children}</div>
    </div>
  );
}

function DefItem({ term, children }: { term: string; children: React.ReactNode }) {
  return (
    <li>
      <span className="text-white/75 font-medium">{term}</span>
      {" means "}
      {children}
    </li>
  );
}

function CookieItem({ type, cookieType, admin, children }: { type: string; cookieType: string; admin: string; children: React.ReactNode }) {
  return (
    <div className="border-l border-white/10 pl-4">
      <p className="text-white/70 font-medium mb-1">{type}</p>
      <p className="text-[12px] text-white/35 mb-2">Type: {cookieType} · Administered by: {admin}</p>
      <p>{children}</p>
    </div>
  );
}
